### ISSUE TITLE
The test result is invalid in Tampermonkey

### ISSUE THREAD

**Issue by dnknn** [mayank992/Multi-Line-Text-Selection#1]
> Hi~ , I really want this kind of lightweight script to achieve multi-point `getSelection()` by holding down `Ctrl`

- https://github.com/mayank992/Multi-Line-Text-Selection/blob/master/contentScript.js

<details><summary>Details</summary>

	 * I pasted this script code into the Tampermonkey editor,
	 * As a result, the test found that it did not have any effect.
- Can you make it into the form of User-JavaScript?
	
		.user.js

[217_12130905](https://user-images.githubusercontent.com/10995302/125234007-57fc4880-e312-11eb-8962-11f5cb8a838e.png)

</details>

**Comment by mayank992** [comment]
Hi, @dnknn 
Please change this line 94

`wrapper.style = "background-color: #accef7";`

**Comment by mayank992** [comment]
Hi, @dnknn

I think you just need to replace line 94
`wrapper.setAttribute('class', '__highlight_text__');`

with 
`wrapper.style = "background-color: #accef7";`.

Please let me know if it solved your issue. On my system by changing this its working fine.

**Comment by dnknn** [comment]
Thank you so much for your help! Yes, It finally works!!!

- - > Recommend 2 extensions for you :
- https://chrome.google.com/webstore/detail/hpihdokfdmmghaclaojfpmbckkhjgebc
	 * Automatic copy (with notification interaction design)
- https://github.com/ssborbis/ContextSearch-web-ext/tree/development
	 * Can cooperate to complete Multi-Text-Selection search

**Comment by dnknn** [comment]
> `wrapper.setAttribute('class', '__highlight_text__');`

```js
	wrapper.classList.add(`__highlight_text__`);
```
I think this way to increase the wording of the `class` will be more standardized/standard/high-performance ^_^,
Then can use [Stylus](https://chrome.google.com/webstore/detail/clngdbkpkpeebahjckkjfobafhncgmne) to customize the CSS-style

**Comment by dnknn** [comment]
@mayank992 
Hello :) I want to ask you, is this function not available in the edit box?

- **the edit box:** 
	 - `input[type=text]`
	 - `textarea`
	 - `isContentEditable` or css `[contenteditable=true]`

```js
	event.target.matches(`input[type=text] , textarea`) || event.target.isContentEditable
```

**Comment by mayank992** [comment]
Hello @dnknn,
No, This script does not support selection in the case of form elements.

**Approach I am using:** I am wrapping the text nodes into another HTML element (more specifically span) and applying CSS (background-color) on that element so that it looks like the text is selected.

**Problem with form Elements:** Everything inside a form element is just the plain text. So, I cannot apply the approach mentioned above inside these elements.

**Solution:** Try to use the approach mentioned in this [article](https://codersblock.com/blog/highlight-text-inside-a-textarea/) for Form elements and see if it solves your problem.

**Comment by dnknn** [comment]
> **Solution:** Try to use the approach mentioned in this [article](https://codersblock.com/blog/highlight-text-inside-a-textarea/) for Form elements and see if it solves your problem.

Thanks for sharing, but it's another function, it just highlights specific defined words/RegExp-words

**Comment by mayank992** [comment]
Yes, I know, but I think we can easily modify this approach to make it work for multi-line text select in **textarea**.

**Comment by dnknn** [comment]
`.isContentEditable` or `div[contenteditable=true]`  this can be used, it is a `div` element

**Comment by mayank992** [comment]
Yes, we can use this. Didn't know about this flag `contenteditable`. Thanks.
